server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Esto es vital para Angular: redirige cualquier ruta 404 al index.html
    # permitiendo que el router interno de Angular funcione
    location / {
        try_files $uri $uri/ /index.html;
    }
}
