server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy Inverso para evadir el CORS
    location /api/ {
        proxy_pass https://satori-backend-production.up.railway.app/api/;
        proxy_set_header Host satori-backend-production.up.railway.app;
        proxy_ssl_server_name on;
    }

    # Esto es vital para Angular: redirige cualquier ruta 404 al index.html
    # permitiendo que el router interno de Angular funcione
    location / {
        try_files $uri $uri/ /index.html;
    }
}
