spring.application.name=Backend
server.port=8080
server.forward-headers-strategy=framework

# Configuracion limpia de SpringDoc OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
